### ISSUE TITLE
need to include proto/sharedstreets.js and  proto/sharedstreets.ts in release build?

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/sharedstreets-pbf#3]
Got this when including the package via "yarn add sharedstreets/sharedstreets-pbf":

```
ERROR in ./node_modules/sharedstreets-pbf/index.ts
Module not found: Error: Can't resolve './proto/sharedstreets' in '/Users/kpw/workspace/react-redux-typescript-boilerplate/node_modules/sharedstreets-pbf'
 @ ./node_modules/sharedstreets-pbf/index.ts 4:12-44
 @ ./src/layers/sharedstreets.ts
 @ ./src/containers/Map/index.tsx
 @ ./src/containers/index.ts
 @ ./src/containers/App/index.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./index.tsx
```

Resolved by building and adding 

- proto/sharedstreets.js
- proto/sharedstreets.ts 

to "./node_modules/sharedstreets-pbf/proto/" in my project.

**Comment by DenisCarriere** [comment]
Which version are you using? You might be using an older version?

Make sure you delete the `yarn.lock` file and then re-install.

```
$ yarn add sharedstreets-pbf
```

You can inspect the latest builds by going to https://unpkg.com/sharedstreets-pbf@0.3.1/proto/ that way you can confirm if you are using the "latest" build.

I'll publish a "patch" release to make sure everything is current to this repo.

@kpwebb I'll make a "dummy" webpack repo and see if it works externally, haven't got that far yet.

**Comment by DenisCarriere** [comment]
@kpwebb Released a new build `v0.4.0` have a try again.

**Comment by DenisCarriere** [comment]
I've started a repo for boilerplate examples, I've included `create-react-app` already and it works for both `sharedstreets` & `sharedstreets-pbf`.

https://github.com/sharedstreets/sharedstreets-examples/blob/master/create-react-app

You'll just need to open your Google Chrome inspector.

![image](https://user-images.githubusercontent.com/550895/35479556-5419f9c4-03c8-11e8-9840-cc36c40bc2e6.png)

**Comment by DenisCarriere** [comment]
Also got Webpack to work (using Javascript, didn't try Typescript yet).

https://github.com/sharedstreets/sharedstreets-examples/blob/master/webpack

![image](https://user-images.githubusercontent.com/550895/35479628-16ff9394-03ca-11e8-8445-90422095cff0.png)

**Comment by kpwebb** [comment]
Ah cool, the 0.4.0 release works! Thanks!

And the examples are super useful, thanks!

**Comment by DenisCarriere** [comment]
> And the examples are super useful, thanks!

Agreed! 😄 Even for myself I get confused how to set up a basic boilerplate for "X" platform.

A few more I'd like to do is:

- [VueJS](https://vuejs.org/)
- [Rollup](https://rollupjs.org/)

Feel free to submit more suggestions for examples via issues:

https://github.com/sharedstreets/sharedstreets-examples
